services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    hostname: mssqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mudar@123"
      MSSQL_PID: "Evaluation"
    ports:
      - 1435:1433
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
  
networks:
  mssqlserver-network:
    external: true